language: cpp

cache:
  apt: true
  directories:
  - $HOME/googletest

matrix:
  include:
    - compiler: gcc
      sudo: required
      dist: trusty
      before_install:
        - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50
      install:
        - gem install coveralls-lcov
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lcov
      env:
        - COMPILER=g++-5
        - CXX=g++-5
        - CC=gcc-5
      before_script:
        - export CXX=g++-5
      after_success:
        - (cd build && bash generateAndSubmitCoverallsReport.sh && cd ..)
    - compiler: clang
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-5
            - clang-4.0
      env:
        - COMPILER=clang++-4.0
        - CXX=clang++-4.0
        - CC=clang-4.0
      before_script:
        - export CC=clang-4.0
        - export CXX=clang++-4.0

script:
  - ( cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER ../ && make -j VERBOSE=yes && make runTests && cd .. )
  